/**
 * Brand Application
 *
 * Applies brand configuration to document templates, AI outputs,
 * and generated content. Acts as a brand "skill" layer.
 */

import type { BrandConfig } from './types'

/** CSS string for embedding brand styles in generated documents */
export function generateBrandCSS(config: BrandConfig): string {
  return `
    :root {
      --brand-primary: ${config.colors.primary};
      --brand-primary-fg: ${config.colors.primaryForeground};
      --brand-secondary: ${config.colors.secondary};
      --brand-secondary-fg: ${config.colors.secondaryForeground};
      --brand-accent: ${config.colors.accent};
      --brand-accent-fg: ${config.colors.accentForeground};
      --brand-bg: ${config.colors.background};
      --brand-fg: ${config.colors.foreground};
      --font-heading: ${config.fonts.heading};
      --font-body: ${config.fonts.body};
      --font-mono: ${config.fonts.mono};
    }
    body { font-family: var(--font-body); color: var(--brand-fg); background: var(--brand-bg); }
    h1, h2, h3, h4, h5, h6 { font-family: var(--font-heading); color: var(--brand-primary); }
    .brand-header { background: var(--brand-primary); color: var(--brand-primary-fg); padding: 24px 32px; }
    .brand-accent { color: var(--brand-accent); }
    .brand-footer { border-top: 2px solid var(--brand-primary); padding-top: 16px; margin-top: 32px; font-size: 12px; color: var(--brand-secondary); }
  `.trim()
}

/** Generate a document header HTML with brand applied */
export function generateBrandedHeader(config: BrandConfig): string {
  const logo = config.logo.primary
    ? `<img src="${config.logo.primary}" alt="${config.logo.altText}" style="max-height: 48px; margin-right: 16px;" />`
    : ''

  return `
    <div class="brand-header" style="background: ${config.colors.primary}; color: ${config.colors.primaryForeground}; padding: 24px 32px; display: flex; align-items: center;">
      ${logo}
      <div>
        <h1 style="margin: 0; font-family: ${config.fonts.heading}; font-size: 24px;">${config.companyName}</h1>
        ${config.tagline ? `<p style="margin: 4px 0 0; opacity: 0.9; font-size: 14px;">${config.tagline}</p>` : ''}
      </div>
    </div>
  `.trim()
}

/** Generate a document footer HTML with brand applied */
export function generateBrandedFooter(config: BrandConfig): string {
  const parts = [config.companyName]
  if (config.website) parts.push(config.website)

  return `
    <div class="brand-footer" style="border-top: 2px solid ${config.colors.primary}; padding-top: 16px; margin-top: 32px; font-size: 12px; color: ${config.colors.secondary};">
      <p>${parts.join(' · ')}</p>
      <p>Generated by DriverOS</p>
    </div>
  `.trim()
}

/**
 * Build AI prompt context from brand config.
 * Injected into system prompt so AI outputs match brand voice.
 */
export function buildBrandPromptContext(config: BrandConfig): string {
  if (!config.companyName) return ''

  const parts = [
    `## Brand Voice Guidelines for ${config.companyName}`,
    `Tone: ${config.voice.tone}`,
    `Style: ${config.voice.style.join(', ')}`,
    `Refer to customers as: "${config.voice.customerTerm}"`,
    `Refer to the team as: "${config.voice.teamTerm}"`,
  ]

  if (config.voice.avoids.length > 0) {
    parts.push(`NEVER use these words/phrases: ${config.voice.avoids.join(', ')}`)
  }

  if (config.voice.examplePhrases.length > 0) {
    parts.push(`Example phrases that sound like this brand:`)
    for (const phrase of config.voice.examplePhrases) {
      parts.push(`- "${phrase}"`)
    }
  }

  if (config.notes) {
    parts.push(`Additional guidelines: ${config.notes}`)
  }

  return parts.join('\n')
}

/**
 * Wrap document content in a branded HTML template.
 */
export function wrapInBrandedTemplate(config: BrandConfig, title: string, bodyHtml: string): string {
  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title} - ${config.companyName}</title>
  <style>${generateBrandCSS(config)}</style>
</head>
<body style="max-width: 800px; margin: 0 auto; padding: 0;">
  ${generateBrandedHeader(config)}
  <div style="padding: 32px;">
    ${bodyHtml}
  </div>
  ${generateBrandedFooter(config)}
</body>
</html>
  `.trim()
}
